### ISSUE TITLE
Is the paper available?

### ISSUE THREAD

**Issue by jakubLangr** [deepakbaby/se_relativisticgan#1]
Hi I'm writing a book about GANs (http://bit.ly/gan-book) and I'm looking for practical applications of the RelativisticGAN. Is the paper available anywhere or could you PM me it? just for the purposes of last chapter.

**Comment by deepakbaby** [comment]
Hi Jakub,

The paper is accepted for publication at IEEE-ICASSP, May 2019. I can send
you the draft if you could mail me directly to deepak.baby@ugent.be,

Regards,
Deepak
