### ISSUE TITLE
about the evaluation

### ISSUE THREAD

**Issue by LG-SS** [deepakbaby/se_relativisticgan#2]
thank you for your repo. I reproduce your experiments, however, I find that PESQ, CD and LLR aren't consistent with the paper. For CD and LLR , I used the matlab code involved in the book "Speech Enhancement: Theory and Practice".  Would you like to provide your evaluation code?

**Comment by deepakbaby** [comment]
I used the evaluation scripts from the REVERB challenge. You can download them from [here](https://reverb2014.dereverberation.com/tools/REVERB-SPEENHA.Release04Oct.zip). Let me know if you still find issues reproducing the results.

For PESQ evaluation, I used the PESQ source code and compiled it on my machine. Then I used a matlab wrapper to run the evaluation (Downloaded from [here](https://www.mathworks.com/matlabcentral/fileexchange/33820-pesq-matlab-wrapper/)). The comment section of this link also has other useful PESQ versions (in python, mex-file,..).
