### ISSUE TITLE
Project version

### ISSUE THREAD

**Issue by czh-learn** [deepakbaby/se_relativisticgan#4]
Hello, Can you tell me what is the version of the framework for your project?

**Comment by deepakbaby** [comment]
It should be working fine with the latest versions of keras and tensorflow. Let me know if you encounter any version related issues.

**Comment by czh-learn** [comment]
> It should be working fine with the latest versions of keras and tensorflow. Let me know if you encounter any version related issues.
Hello, ok, the issues I encounter is:
 ''models.py, line 87, in generator
 dec_out.set_shape([None, nrows, 1 , ncols]) # for correcting shape issue with conv2dtranspose
AttributeError: 'TensorVariable' object has no attribute 'set_shape'', this code run error,''  how can i solve this ,i have tried many methods.thank you very much for your reply.

**Comment by deepakbaby** [comment]
Are you using theano backend?
