### ISSUE TITLE
KeyError on preemph

### ISSUE THREAD

**Issue by Sixtease** [deepakbaby/se_relativisticgan#6]
The script `run_aecnn.py` crashes with following error

```
Traceback (most recent call last):
  File "run_aecnn.py", line 160, in <module>
    cleanwavs = data_preprocess(cleanwavs, preemph=opts['preemph'])
KeyError: 'preemph'
```

Should I initialize opts['preemph'] to some specific value?

**Comment by Sixtease** [comment]
I tried initializing with 0 and the training runs, so let's see. :-)

**Comment by deepakbaby** [comment]
Set it as 
`opts ['preemph'] = 0.95`
