### ISSUE TITLE
KeyError: 'D_real_target'

### ISSUE THREAD

**Issue by Sixtease** [deepakbaby/se_relativisticgan#7]
in `run_lsgan_se.py` on line 196, `opts['D_real_target']` throws a KeyError. I haven't been able to figure out if it's a typo or what value to set it to.

**Comment by deepakbaby** [comment]
Hi,

Thanks for pointing this out.

`opts ['D_real_target']` in LS GAN can be used for label smoothing. For normal SEGAN, this is set to 1., but can be changed to 0.9 or 0.95 if you want to apply label smoothing (which is found to improve the stability during training). The code is updated with with default value set to 1.
