### ISSUE TITLE
framework version(version of tensorflow and keras)

### ISSUE THREAD

**Issue by czh-learn** [deepakbaby/se_relativisticgan#8]
hello. I also meet some questions and can you be so kind to specify the package versions needed?
the problem I meet is 'ncols = dec_out.get_shape().as_list()[-1]
AttributeError: 'TensorVariable' object has no attribute 'get_shape''
 Thank you very much!

**Comment by Huer-H** [comment]
Hello, this is my version information,
tf-gpu==1.9.0
keras==2.2.0
I hope to help you.

**Comment by deepakbaby** [comment]
Hi,
My package versions were
Keras v2.3.1 
Tensorflow v1.13.2
