### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by LiChao610** [deepakbaby/se_relativisticgan#9]
Hello,
    The dataset (11572 utts) in your paper is inconsistent with that (23075 utts) in the script prepare_data.py, and I can't get the result or similar results in your paper using the dataset in your paper. Can you give some guidance？
    Thank you very much!

**Comment by deepakbaby** [comment]
The 11572 wav files used as the training data can be found in the `train_wav.txt` file. In fact, the `prepare_data.py` script reads from the `train_wav.txt` file for preparing the training data. So it should be fine.
